
#pragma once
#ifndef __PERIPH_CONFIG_H_
#define __PERIPH_CONFIG_H_

/* PA13, PA14 - SWD - DON'T USE!!! */
/*        PA11, PA12 - USB		   */


#define V_MEASURE_PORT			GPIOA
#define V_MEASURE_PIN			GPIO_Pin_0

#define S6D0164_DATA_PORT		GPIOA
#define S6D0164_CTRL_PORT		GPIOC
#define S6D0164_CTRL_PIN_RESET	GPIO_Pin_4
#define S6D0164_CTRL_PIN_RD		GPIO_Pin_3
#define S6D0164_CTRL_PIN_WR		GPIO_Pin_2
#define S6D0164_CTRL_PIN_RS		GPIO_Pin_1
#define S6D0164_CTRL_PIN_CS		GPIO_Pin_0


#endif //__PERIPH_CONFIG_H_
